version: 2
jobs:
  build:
    docker:
      - image:  mcr.microsoft.com/dotnet/sdk:6.0
    steps:
      - checkout
      - run:
          name: Restore
          command: dotnet restore
          working_directory: src
      - run:
          name: Build
          command: dotnet build -c Release
          working_directory: src
      # - run:
      #     name: Running Tests
      #     command: dotnet test
      #     working_directory: MyProject.Tests
      - setup_remote_docker:
          docker_layer_caching: true
      # - run:
      #     name: Build and push Docker image
      #     command: |
      #       docker build -t HelloWorldPanoptica .
      #       echo $DOCKER_PWD | docker login -u $DOCKER_LOGIN --password-stdin
      #       docker tag boku herocod3r/MyProject
      #       docker push herocod3r/MyProject

      - portshiftscanner/scan-image:
          requires:
            - docker-build
          context: portshift-credentials
          image_name: <image-name>
          image_tag: <image-tag>
          access_key: ${ACCESS_KEY}
          secret_key: ${SECRET_KEY}